name: NodeJS with Webpack
permissions: write-all

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - uses: volta-cli/action@v4

      - name: Install
        run: npm ci

      - name: Versions
        run: |
          node --version
          npm --version

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run build

      - name: Cypress (with coverage)
        run: npm run cy:run:cov

      - name: NYC report
        if: success() || failure()
        run: npm run cov:report

      - name: Coverage check
        if: success() || failure()
        run: npm run cov:check

      - name: Archive code coverage results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage/lcov-report/

      - name: Monitor coverage
        if: success() || failure()
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: 'coverage/clover.xml'

      - name: Publish Cypress JUnit report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/reports/cypress/*.xml'
          check_name: 'Cypress Test Report'
          detailed_summary: true
  # ═══════════════════════════════════════════════════════════════
  # PUBLISH: With specific commit messages, beta versions published always
  # ═══════════════════════════════════════════════════════════════
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          gitmsg="${{ github.event.commits[0].message }}"
          echo "Commit: $gitmsg"

          if [[ "$gitmsg" =~ "[patch]" ]] || [[ "$gitmsg" =~ "[fix]" ]]; then
            npm run publish:patch && git push --tags
          elif [[ "$gitmsg" =~ "[minor]" ]]; then
            npm run publish:minor && git push --tags
          elif [[ "$gitmsg" =~ "[major]" ]]; then
            npm run publish:major && git push --tags
          else
            echo "Publishing beta"
            npm run publish:beta || true
          fi
